#ifndef CONFIG_H
#define CONFIG_H

#define CHANNEL_A     0U
#define CHANNEL_B     1U
#define CHANNEL_C     2U
#define CHANNEL_D     3U
#define CHANNEL_E     4U
#define CHANNEL_COUNT 5U

#define CHECK_TIMEOUT_MS 5000U

#define PWM_DEFAULT_FREQUENCY_HZ 500000U
#define PWM_DEFAULT_DUTY_CYCLE   0U
#define PWM_DEFAULT_DEAD_TIME_NS 20U

#define PWM_MIN_FREQUENCY_HZ 100000U
#define PWM_MAX_FREQUENCY_HZ 800000U
#define PWM_MIN_DUTY_CYCLE   0U
#define PWM_MAX_DUTY_CYCLE   850U
#define PWM_MIN_DEAD_TIME_NS 5U
#define PWM_MAX_DEAD_TIME_NS 300U

#define LED_BUS_ON_MV  35000U
#define LED_BUS_OFF_MV 34000U

#define TELEM_SWEEP_PERIOD_MS 40U
#define TELEM_STEP_TIMEOUT_MS 5U

#define ANALOG_PERIOD_MS 1U

#endif
